################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
BTPSKRNL.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Bluetopia/btpskrnl/NoOS/BTPSKRNL.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="BTPSKRNL.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BTPSVEND.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Bluetopia/btpsvend/BTPSVEND.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="BTPSVEND.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BTVS.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Bluetopia/btvs/source/BTVS.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="BTVS.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HAL.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Hardware/HAL.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="HAL.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HCITRANS.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Bluetopia/hcitrans/NoOS/HCITRANS.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="HCITRANS.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HFPDemo.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Sample/HFPDemo/HFPDemo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="HFPDemo.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Main.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Sample/HFPDemo/NoOS/Main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="Main.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

TivaWareLib.obj: C:/ti/Connectivity/CC256X\ BT/CC256x\ M4\ Bluetopia\ SDK/v1.2\ R2/Cortex_M4/Sample/HFPDemo/TivaWareLib.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" --cmd_file="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS/CCSv5\..\..\..\..\BuildScripts\TivaWarePath_DK_TM4C123G_CCS.txt"  -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O2 --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Sample/HFPDemo" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Hardware/dk-tm4c123g" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpskrnl/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/hcitrans/NoOS" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btpsvend" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/btvs/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/include" --include_path="C:/ti/Connectivity/CC256X BT/CC256x M4 Bluetopia SDK/v1.2 R2/Cortex_M4/Bluetopia/profiles/hfp/include" --define=PART_TM4C123GH6PGE --define=TARGET_IS_BLIZZARD_RB1 --define=DEBUG_ZONES=0 --define=__SUPPORT_CC256XB_PATCH__ --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="TivaWareLib.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


